name: mericsong
description: A data-driven engineer
meta_description: "mericsong"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 5
baseurl: ""
domain_name: "http://songmeric.github.io"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Meric Song"

# Disqus config
disqus-shortname: ""
