name: IB Engineering
description: IB 전문 온라인 학원
meta_description: "Online IB tutoring service"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
domain_name: "http://ibengineering.kr"
baseurl: "" # the subpath of your site, e.g. "/blog"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Your Name"

# Disqus config
disqus-shortname: ""
